#!/bin/bash

function fp() {
	git format-patch -$1;
}
function commsg() {
	args=
	for arg in $@
	do
	if [ "$arg" != "c" ]; then if [ "$arg" != "p" ]; then args="$args$arg " ; fi; fi
	done
	if [ -z "$args" ]; then read commitmsg; else commitmsg="$args"; fi
	$echo git commit -sS -m "$commitmsg"
}

function edate() {
git commit --amend --no-edit --date="$1 $2"
};

case $1 in
	ch)
		case $2 in
		*con|*continue) git cherry-pick --continue;;
		*abort) git cherry-pick --abort;;
		*) git cherry-pick -sS $2 $3 $4;;
		esac;;
	am) git am -3 $2;;
	m) git merge --signoff $2;;
	ra) git remote add $2 $3;;
	c) commsg $@;;
	a) rm -rf *.patch; git add .; git commit -S --signoff --amend;;
	*now) edate now;;
	date) edate "$3 $4";;
	f) git fetch --tags caf;;
	p) commsg $@; git format-patch -$2;;
esac
