#!/bin/bash
# $1 - repo
# $2 - project
# $3 - tag
case $1 in
	*googlesource*|AOSP|aosp)
		repo="$AOSP";
	if [ $3 == "pie-gsi" ]; then TAG=pie-gsi;
	else TAG=android-9.0.0_$3; fi ;;
	*codeaurora*|CAF|caf)
		repo="$CAF";
		TAG=$3;;
esac;
case $2 in
	auto) proj=$(echo `pwd` | sed -e 's/\/home\/ksrt12\/havoc\///');;
	*) proj=$2;;
esac;
$echo git pull --signoff --gpg-sign $repo/$proj $TAG;
