#!/bin/bash
# $1 - repo
# $2 - tag
# $3 - project

case $1 in
	*google*|AOSP|aosp)
		repo="https://android.googlesource.com/platform";
		tag=android-$2;
		;;
	*codeaurora*|CAF|caf)
		repo="https://git.codelinaro.org/clo/la/platform";
		tag=$2;
		;;
esac;
if [ -z "$3" ]; then
	proj=$(echo `pwd` | sed -e 's/\/home\/ksrt12\/havoc\///' | sed -e 's/\qcom\/opensource/qcom-opensource/');
else
	proj="$3.git/";
fi;
$4 git pull --no-edit --signoff --gpg-sign --stat --log --commit $repo/$proj $tag;
