#!/bin/bash
# $1 - repo
# $2 - project
# $3 - tag
case $1 in
	*googlesource*|AOSP|aosp)
		repo="$AOSP";
		TAG=android-9.0.0_$3;;
	*codeaurora*|CAF|caf)
		repo="$CAF";
		TAG=LA.UM.7.5.$3-8x96.0;;
esac;
case $2 in
	auto) proj=$(echo `pwd` | sed -e 's/\/home\/ksrt12\/havoc\///');;
	*) proj=$2;;
esac;
$echo git pull --signoff --gpg-sign $repo/$proj $TAG;
