#!/bin/bash
if [ -n "$2" ]; then out=$2; else out=signed.$1; fi
java -Xmx2048m -Djava.library.path=/home/ksrt12/havoc/out/host/linux-x86/lib64 -jar /home/ksrt12/havoc/out/host/linux-x86/framework/signapk.jar -w /home/ksrt12/havoc/build/target/product/security/testkey.x509.pem /home/ksrt12/havoc/build/target/product/security/testkey.pk8 $1 $out
