#!/bin/bash
case $1 in
	*cherryplus*) dev=cherryplus;;
	*gemini*) dev=gemini;;
esac
case $1 in
	*yberia*) rom=syberia;;
	*avoc*) rom=havoc;;
esac
$echo rsync --progress -e ssh $1 ksrt12@frs.sourceforge.net:/home/frs/project/havoc-gemini/$rom/$dev/
