#!/bin/bash

if [ -z "$khw_id" ]; then khw_id=d32b393b; fi
if [ -n "$1" ]; then num=$1; else num=$((`nproc` - 2));fi
sudo ~/xmrig/build/xmrig --coin monero --url monero.kryptex.network:7777 --user "4DSQMNzzq46N1z2pZWAVdeA6JvUL9TCB2bnBiA3ZzoqEdYJnMydt5akCa3vtmapeDsbVKGPFdNkzqTcJS8M8oyK7WGj2eezRPM372XRSQi.v2$khw_id" -p x --retries=2 --retry-pause=2 --threads=$num
